### ISSUE TITLE
Compact printed report

### ISSUE THREAD

**Issue by bhirsz** [bhirsz/robotframework-sherlock#33]
Make more compact printed report (current print report can be optionally renamed to print_tree). Output could look like (taken from https://github.com/Snooz82/robotframework-browser-migration):

    +----------------------------------+-------+---------+
    | Keyword                          | count | parents |
    +----------------------------------+-------+---------+
    | Checkbox Should Be Selected      | 10    | 2       |
    | Checkbox Should Not Be Selected  | 10    | 2       |
    | Clear Element Text               | 1     | 1       |
    | Click Button                     | 4     | 4       |
    | Click Element                    | 48    | 20      |

**Comment by mnojek** [comment]
Looks cool but I do not like the 'parents' header. Anyway, I don't have a better idea now.

**Comment by bhirsz** [comment]
Yeah me either but I dont have better alternative. Unique calls?

**Comment by mnojek** [comment]
Depends on what it will show. What about changing `count` to `executions` (so it will count all real executions including loops) and `parents` to `calls` (it will count places where it is called)?

**Comment by bhirsz** [comment]
Current format:
```
Directory: 2_Variable_Import
    Resource: dev.resource
      Timings:
        Total elapsed    Shortest execution    Longest execution    Average execution
        00:00:00:000     00:00:00:000          00:00:00:000         00:00:00:000

      Keywords:
        +---------+------------+------------+--------------+
        | Keyword | Executions | Complexity |   Elapsed    |
        +---------+------------+------------+--------------+
        | Keyword |     1      |     1      | 00:00:00:000 |
        +---------+------------+------------+--------------+
    Resource: preprod.resource
      Timings:
        Total elapsed    Shortest execution    Longest execution    Average execution
        00:00:00:00      00:00:00:00           00:00:00:00          00:00:00:00

      Keywords:
        +---------+------------+------------+---------+
        | Keyword | Executions | Complexity | Elapsed |
        +---------+------------+------------+---------+
        | Keyword |     0      |     1      |         |
        +---------+------------+------------+---------+
```
I'm still working on the presentation part - and some features like calls/parents is still missing. I'm wondering what would be best headers to use for keywords - keyword name, executions, calls/parent are given. Complexity should be also part of standard. Timings are problematic - I can use total, min, max and avg elapsed time but I don't think we should use them all - maybe total and/or avg will suffice (timestamp format is separate discussion in other issue).

**Comment by bhirsz** [comment]
Other example:
```
Directory: 8_html_report
    Directory: resources
        Directory: keywords
            Resource: keywords.resource
              Timings:
                Total elapsed    Shortest execution    Longest execution    Average execution
                00:00:02:012     00:00:00:000          00:00:02:012         00:00:00:670

              Keywords:
                +-----------------------+------------+------------+--------------+
                | Keyword               | Executions | Complexity |   Elapsed    |
                +-----------------------+------------+------------+--------------+
                | Decrease By One       |     5      |     2      | 00:00:00:000 |
                | Keyword From Resource |     1      |     1      | 00:00:00:000 |
                | Not Used              |     0      |     1      |              |
                | Other Keyword         |     1      |     1      | 00:00:02:012 |
                +-----------------------+------------+------------+--------------+
```

**Comment by mnojek** [comment]
If you already precede the keyword table with "Keywords:", I think you can use the "Name" word in the header above the keyword name. 
Definitely shortest and longest timings can be omitted - it doesn't bring that much value. 
What actually are these timings? Shouldn't i t be listed for each keyword, not for a resource?

**Comment by bhirsz** [comment]
I agree on Keyword ->Name.

Timings under resource list total timings for all keywords under given resource. So if you have ie. 10 keywords, where fastest is 1s and slowest is 10s and it's gradually increasing by 1s for each keywords, then total will be 55s, shortest 1s, longest 10s, avg 5,5s. I guess that average for whole resource is not useful information (as we can have very slow or fast keywords). Same for shortest/longest - since there could be several execution of multiple keywords, it would be hard to see which one is the fastest. And slowest can be found by looking at keyword timing.

Then you can list the same timings but for each keywords - each keyword can be executed multiple times and it's counting all executions but only for given keyword (as opposed to resource wide timing).

**Comment by mnojek** [comment]
BTW I think that "Timings" is not a proper word. IMO, it should be just "Time" or "Elapsed time". maybe even another word (not sure which one) would be better?

And I will print the average time for each keyword and mark it with the header name "Average time" instead of "Elapsed" which is not precise and I am not sure what it is showing. Maybe "Total time" would also be helpful to see where your tests spend the most time?

Also, in the header I would provide the unit, so in "Elapsed time" it should be "Elapsed time [s]". Maybe you can even drop the milliseconds and provide just a number, e.g. "80" instead of "00:01:20:534' if we already now the unit. It will be easier to compare the numbers.

Also, for the "timings" (as you call it) for a resource, I would also provide a table - it will increase the readability.

**Comment by bhirsz** [comment]
Yes, "timings" doesn't sound right - > I can go with "Elapsed time" for now. 

Agree on average - I can add Average time and rename Elapsed to Total time for keyword.

I will change the format of the timestamps -> I can either go with [s] in header name or use human readable timestamp (14 min 33 s). The first option makes it easier to compare (111s vs 8 s) but the other is easier to read (especially for long tests, though I doubt there will be keywords with hours spent on them. Days and weeks are extremely not likely ;)). I will go with [s] for now.

Agree on table on resource level.

**Comment by bhirsz** [comment]
After latest changes (not yet merged):

```
Directory: 8_html_report
    Directory: resources
        Directory: keywords
            Resource: keywords.resource
              Elapsed time:
                +-------------------+------------------------+-----------------------+-----------------------+
                | Total elapsed [s] | Shortest execution [s] | Longest execution [s] | Average execution [s] |
                +-------------------+------------------------+-----------------------+-----------------------+
                |         2         |           0            |           2           |           1           |
                +-------------------+------------------------+-----------------------+-----------------------+

              Keywords:
                +-----------------------+------------+------------+------------------+----------------+
                | Name                  | Executions | Complexity | Average time [s] | Total time [s] |
                +-----------------------+------------+------------+------------------+----------------+
                | Decrease By One       |     5      |     2      |        0         |       0        |
                | Keyword From Resource |     1      |     1      |        0         |       0        |
                | Not Used              |     0      |     1      |                  |                |
                | Other Keyword         |     1      |     1      |        2         |       2        |
                +-----------------------+------------+------------+------------------+----------------+
    Suite: test.robot
```
